# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
#my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@service_container"]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: mainMenu }

    app.meta_menu:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMetaMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: metaMenu }

