# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@service_container"]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: mainMenu }

    app.meta_menu:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMetaMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: metaMenu }